name:Sandy guarino

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |repo init -u git://github.com/CyanogenMod/android.git -b cm-14.1
Then to sync up:
        echo Add other actions to build,
        echo test, and deploy your project.
